services:
  park_easy_app:
    container_name: park_easy_app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: True
    tty: True
    restart: on-failure
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - envs/.env
    